### ISSUE TITLE
Detect connected devices

### ISSUE THREAD

**Issue by Bibo-Joshi** [sputnikdev/eclipse-smarthome-bluetooth-binding#44]
Hi there!
Thanks for your great work on the binding!
While testing in openHAB, I stumbled upon an issue: When the device I want to detect is paired to another, it will be marked as offline. Since I only want to know, if it is running, I would like to have it marked as online even if paired. 
Is there some way to make this work? Is it even technically possible?
I'd be grateful for an reply.
King regards,

Hinrich

**Comment by vkolotov** [comment]
Hi @Bibo-Joshi , it depends on what you mean by "paired". In Bluetooth world "paired" and "connected" are different things. Connected - it is when two devices established a link and talk to each other. Paired (or "trusted") - when a device is marked as a trusted device so that when that device tries to make a connection, the other device let it to establish connection automatically (afaik).
So if you mean "connected" (I assume), then it is not possible to detect of either of those connected devices are online or not, until they get disconnected from each other. That's how Bluetooth works. 

It might be possible to detect if they are online of those devices report it somehow in the Internet or in a different way (eg. not via Bluetooth standard stack), but this would be beyond the binding.

**Comment by Bibo-Joshi** [comment]
Ah, okay.
Thanks for your kind response anyway.
I'll change the issue title to `Detect connected devices`. Thanks for the clarification.
